AcessoBolsas/AcessoBolsas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from AcessoBolsas.views import HomeView
from AcessoBolsas.views import SignUp
from AcessoBolsas.views import SignIn
from user.views import (
    loginUser,
    logoutUser,
    registerUser,
    myAccountUser,
)
from institution.views import (
    loginInstitution,
    logoutInstitution,
    createInstitution,
    myAccountInstitution,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView , name='home'),
    path('user/', include('user.urls')),
    path('<username>/my_account/', myAccountUser, name='my_account'),
    path('<slugInstitution>/my_account_institution/', myAccountInstitution, name='my_account_institution'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('loginInstitution/', loginInstitution, name='loginInstitution'),
    path('logoutInstitution/', logoutInstitution, name='logoutInstitution'),
    # path('scholarship/', include('scholarship.urls')),
    path('institution/', include('institution.urls')),
    path('sign_in/', SignIn, name='sign_in'),
    path('sign_up/', SignUp, name='sign_up'),
    path('sign_up/institution/', createInstitution, name='sign_up_institution'),
    path('sign_up/user/', registerUser, name='sign_up_user'),
    path('scholarship/', include('scholarship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AcessoBolsas/institution/urls.py
from django.urls import path
from institution import views

app_name ='institution'

urlpatterns = [
    path('<slug>/profile/', views.viewInstitution, name='profile-institution'),
    path('<slug>/edit/', views.editInstitution, name='edit-institution'),
    path('', views.listInstitutions, name='list-institution'),
    path('create/', views.createInstitution, name='create-institution'),
    path('<slug>/delete/', views.deleteInstitution, name='delete-institution'),
    path('institution/<slug:slug>/scholarships/', views.institutionScholarships, name='institution-scholarships'),

]

AcessoBolsas/scholarship/urls.py
from django.urls import path
from scholarship import views

app_name = 'scholarship'

urlpatterns = [
    path('create/', views.createScholarship, name='create-scholarship'),
    path('<slug>/edit/', views.editScholarship, name='edit-scholarship'),
    path('<slug>/profile/', views.viewScholarship, name='profile-scholarship'),
    path('<slug>/delete/', views.deleteScholarship, name='delete-scholarship'),
    path('inscricoes/', views.listar_scholarships_user, name='listar-scholarships-user'),  # Colocando antes do path com slug
    path('', views.listScholarships, name='list-scholarship'),
    path('<slug>/', views.viewScholarship, name='view-scholarship'),
    path('inscrever/<slug>/', views.inscrever_scholarship, name='inscrever-scholarship'),
]

AcessoBolsas/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerUser, name='register-user'),
    path('<slug>/edit/', views.editUser, name='edit-user'),
    path('<slug>/delete/', views.deleteUser, name='delete-user'),
    path('<slug>/profile/', views.viewUser, name='profile-user'),
    path('', views.listUsers, name='list-user'),
]

AcessoBolsas/institution/models.py
from django.db import models
from random import randint
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_delete, pre_save

SLUG_LIST = []

class Institution(models.Model):
    id = models.AutoField(primary_key=True, null=False, blank=False, unique=True)
    nome = models.CharField(max_length=100, null=False, blank=False, unique=True)
    cnpj = models.CharField(max_length=18, null=False, blank=False, unique=True)
    email = models.EmailField(max_length=254, null=False, blank=False, unique=True, default='default@mail.com')
    contato = models.CharField(max_length=50, null=False, blank=False)
    endereco = models.CharField(max_length=255, null=True, blank=True)
    descricao = models.CharField(max_length=1000, null=False, blank=False)
    fotoPerfil = models.ImageField(upload_to='institution', default='default.jpg')
    slug = models.SlugField(blank=True, unique=True)
    checked = models.BooleanField(default=False)
    logged = models.BooleanField(default=False)
    password = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.nome
    

def pre_save_institution_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug_random = 0
        while slug_random not in SLUG_LIST:
            slug_random = randint(1, 1000)
            SLUG_LIST.append(slug_random)
        
        instance.slug = slugify(instance.nome + "-" + str(slug_random))

pre_save.connect(pre_save_institution_receiver, sender=Institution)

AcessoBolsas/institution/forms.py
from django import forms
from institution.models import Institution

class InstitutionRegisterForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = ['nome', 'cnpj', 'email', 'contato', 'endereco', 'descricao', 'fotoPerfil']

class InstitutionUpdateForm(forms.ModelForm):
    class Meta:
        model = Institution
        fields = ['nome', 'cnpj', 'email', 'contato', 'endereco', 'descricao', 'fotoPerfil']

    def save(self, commit=True):
        institution = self.instance
        institution.nome = self.cleaned_data['nome']
        institution.cnpj = self.cleaned_data['cnpj']
        institution.email = self.cleaned_data['email']
        institution.contato = self.cleaned_data['contato']
        institution.endereco = self.cleaned_data['endereco']
        institution.descricao = self.cleaned_data['descricao']

        if self.cleaned_data['fotoPerfil']:
            institution.fotoPerfil = self.cleaned_data['fotoPerfil']

        if commit:
            institution.save()
        return institution

    def clean_email(self):
        email = self.cleaned_data['email']
        if Institution.objects.exclude(pk=self.instance.pk).filter(email=email).exists():
            raise forms.ValidationError('Email "%s" já está sendo utilizado.' % email)
        return email

    def clean_nome(self):
        nome = self.cleaned_data['nome']
        if Institution.objects.exclude(pk=self.instance.pk).filter(nome=nome).exists():
            raise forms.ValidationError('Nome "%s" já está sendo utilizado.' % nome)
        return nome

    def clean_cnpj(self):
        cnpj = self.cleaned_data['cnpj']
        if Institution.objects.exclude(pk=self.instance.pk).filter(cnpj=cnpj).exists():
            raise forms.ValidationError('CNPJ "%s" já está sendo utilizado.' % cnpj)
        return cnpj

AcessoBolsas/institution/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
import random
import logging
import string
from django.views.decorators.csrf import csrf_protect
from institution.models import Institution
from institution.forms import InstitutionRegisterForm, InstitutionUpdateForm
from scholarship.models import Scholarship
from operator import attrgetter

# Create your views here.

@csrf_protect
def createInstitution(request):
    context = {}
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    form = InstitutionRegisterForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        institution = form.save(commit=False)
        institution.save()
        form = InstitutionRegisterForm()
        messages.success(request, 'Instituição cadastrada com sucesso!')
        return redirect('home')
    
    context['form'] = form
    return render(request, 'institution/createInstitution.html', context)


def editInstitution(request, slug):
    context = {}
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    institution = get_object_or_404(Institution, slug=slug)

    if not institution.checked or not institution.logged:
        return redirect("loginInstitution")

    if request.method == 'POST':
        form = InstitutionUpdateForm(request.POST, request.FILES, instance=institution)
        if form.is_valid():
            form.save()
            messages.success(request, 'Instituição atualizada com sucesso!')
            response = redirect('home')
            if request.COOKIES.get('nameInstitution') != institution.nome:
                response.set_cookie('nameInstitution', institution.nome)
                response.set_cookie('slugInstitution', institution.slug)
            return response
        else:
            messages.warning(request, 'Erro ao atualizar a instituição. Tente novamente.')
    else:
        form = InstitutionUpdateForm(instance=institution)

    context['form'] = form
    return render(request, 'institution/editInstitution.html', context)


def viewInstitution(request, slug):
    context = {}
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    institution = get_object_or_404(Institution, slug=slug)
    context['institution'] = institution
    return render(request, 'institution/viewInstitution.html', context)


def deleteInstitution(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    institution = get_object_or_404(Institution, slug=slug)

    if not institution.checked or not institution.logged:
        return redirect("loginInstitution")
    
    if request.POST:
        institution.fotoPerfil.delete()
        institution.delete()
        response = redirect('home')
        response.set_cookie('logged', False)
        response.set_cookie('slugInstitution', None)
        response.set_cookie('nameInstitution', None)
        messages.success(request, 'Instituição excluída com sucesso!')
        return response
    
    context['institution'] = institution
    return render(request, 'institution/deleteInstitution.html', context)


def listInstitutions(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    institutions = Institution.objects.all()
    context['institutions'] = institutions
    return render(request,'institution/listInstitutions.html', context)

def generate_random_password(length=8):

    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(length))

logger = logging.getLogger(__name__)

def loginInstitution(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    if request.method == 'POST':
        cnpj = request.POST.get('cnpj')
        password = request.POST.get('password', None)

        if password:
            # Etapa de verificação de senha
            try:
                institution = Institution.objects.get(cnpj=cnpj)
                if password == institution.password:
                    logout(request)
                    institution.logged = True
                    institution.save()
                    response = redirect('home')
                    response.set_cookie('logged', True)
                    response.set_cookie('slugInstitution', institution.slug)
                    response.set_cookie('nameInstitution', institution.nome)
                    return response
                else:
                    context['error'] = 'Senha incorreta. Tente novamente.'
                    context['cnpj'] = cnpj
            except Institution.DoesNotExist:
                context['error'] = 'Instituição com esse CNPJ não existe.'
        else:
            # Etapa de envio de senha
            try:
                institution = Institution.objects.get(cnpj=cnpj)

                # Gerar uma senha aleatória
                password = generate_random_password()
                institution.password = password
                institution.save()

                # Enviar email para a instituição com a senha gerada
                send_mail(
                    'Sua senha de login',
                    f'Sua senha é: {password}',
                    settings.DEFAULT_FROM_EMAIL,
                    [institution.email],
                    fail_silently=False,
                )
                context['message'] = 'A senha foi enviada para o email cadastrado. Verifique a sua caixa de entrada no email.'
                context['cnpj'] = cnpj
            except Institution.DoesNotExist:
                context['error'] = 'Instituição com esse CNPJ não existe.'
            except Exception as e:
                logger.error(f'Erro ao enviar e-mail: {e}')
                context['error'] = f'Erro ao enviar e-mail: {e}'

    return render(request, 'institution/loginInstitution.html', context)

def logoutInstitution(request):
    institution = Institution.objects.get(slug=request.COOKIES.get('slugInstitution'))
    institution.logged = False
    institution.save()
    response = redirect('home')
    response.set_cookie('logged', False)
    response.set_cookie('slugInstitution', None)
    response.set_cookie('nameInstitution', None)
    return response

def myAccountInstitution(request, slugInstitution):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    
    institution = get_object_or_404(Institution, slug=slugInstitution)
    context['institution'] = institution
    return render(request,'institution/viewInstitution.html', context)

def institutionScholarships(request, slug):
    context = {}
    
    institution = get_object_or_404(Institution, slug=slug)
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    query = request.GET.get('q')
    if query:
        scholarships = Scholarship.objects.filter(titulo__icontains=query, instituicao=institution)
    else:
        scholarships = Scholarship.objects.filter(instituicao=institution).order_by('-titulo')
        
    context['scholarships'] = scholarships
    
    return render(request, 'institution/InstitutionScholarships.html', context)
        
    
    

AcessoBolsas/institution/templates/institution/InstitutionScholarships.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>
    <div class="div-recomendacoes">
        <p class="text-recomendacoes">Bolsas de estudos da instituição {{ nameInstitution }}:</p>
        <div class="recomendacoes">
            <div class="left-column col-lg-7 offset-lg-1">  
                {% for scholarship in scholarships %}
                <div>
                    <div class="container">
                        <div class="row">
                            <div class="card m-auto text-bg-dark">
                                <div class="card-body my-2">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <h2 class="card-titulo">{{ scholarship.titulo }}</h2>
                                    </div>
                                    <hr>
                                    <a href="{% url 'scholarship:profile-scholarship' scholarship.slug %}" style="text-decoration: none !important" class="link-dark">
                                        <div class="container">
                                            <p class="card-text text-bg-dark">{{ scholarship.instituicao }}</p>
                                            <p class="card-text text-bg-dark">{{ scholarship.titulo }}</p>
                                            <p class="card-text text-bg-dark">{{ scholarship.tipoBolsa }}</p>
                                            <p class="card-text text-bg-dark">{{ scholarship.fotoPerfil }}</p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                    <p>Sem Bolsas</p>
                {% endfor %}
            </div>
        </div>
    </div>
</body>





{% endblock content %}

AcessoBolsas/institution/templates/institution/createInstitution.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>
    <p class="voltar" onclick="history.go(-1);"><img src="{% static '\institution\img\seta_back.png' %}" class="img_seta" /><u>Voltar</u></p>
    <div class="div-box">
        <p class="blank1"></p>
        <div class="box">
            <div class="questions">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p class="headerInput">Nome da Instituição: </p>
                    <input type="text" class="inputCadastro" name="nome" placeholder="Nome:" />

                    <p class="headerInput">CNPJ: </p>
                    <input type="number" class="inputCadastro" name="cnpj" placeholder="CNPJ:" />

                    <p class="headerInput">Telefone: </p>
                    <input type="text" class="inputCadastro" name="contato" placeholder="Tel:" />
                    
                    <p class="headerInput">E-mail: </p>
                    <input type="email" class="inputCadastro" name="email" placeholder="E-mail:" />

                    <p class="headerInput">Endereço: </p>
                    <input type="text" class="inputCadastro" name="endereco" placeholder="Endereço:" />

                    <p class="headerInput">Descrição sobre a Instituição: </p>
                    <textarea class="inputCadastro_text_desc" name="descricao"></textarea>
                    
                    {% comment %} {% for field in registrationForm %}
                    <p>
                        {% for error in field.errors %}
                        <p style="color: red;">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    {% if registrationForm.non_field_errors %}
                    <div style="color: red;">
                        <p>{{ registrationForm.non_field_errors }}</p>
                    </div>
                    {% endif %} {% endcomment %}
                    <button type='submit' class="cadastre-se">Cadastre-se</button>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'AcessoBolsas/js/script.js' %}"></script>

</body>

{% endblock content %}

AcessoBolsas/institution/templates/institution/createInstitution1.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Criar Instituição </title>
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_nome" class="form-label">Nome</label>
                <input type="text" name="nome" class="form-control" id="id_nome" placeholder="Nome da instituição" required autofocus>
            </div>
            <div class="mb-3">
                <label for="id_cnpj" class="form-label">CNPJ</label>
                <input type="text" name="cnpj" class="form-control" id="id_cnpj" placeholder="CNPJ da instituição" required>
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="id_email" placeholder="Email da instituição" required>
            </div>
            <div class="mb-3">
                <label for="id_contato" class="form-label">Contato</label>
                <input type="text" name="contato" class="form-control" id="id_contato" placeholder="Contato de instituição" required>
            </div>
            <div class="mb-3">
                <label for="id_endereco" class="form-label">Endereço</label>
                <input type="text" name="endereco" class="form-control" id="id_endereco" placeholder="Endereço de instituição" required>
            </div>
            <div class="mb-3">
                <label for="id_descricao" class="form-label">Descrição</label>
                <textarea name="descricao" rows="10" class="form-control" id="id_descricao" placeholder="Descrição da instituição" required></textarea>
            </div>
            <div class='text-center'>
                <button type='submit' class='btn btn-primary'>Criar Instituição</button>
            </div>
        </form>
    </body>
</html>

AcessoBolsas/institution/templates/institution/deleteInstitution.html
{% load static %}
<!doctype html>
<html lang="en">
    <title>Deletar {{institution.nome}}</title>
    <head>
        <h3 class='text-center'>Deletar Instituição</h3>
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class='text-center'>Tem certeza que deseja deletar esssa instituição?</h3>
            <div class="mt-3 text-center">
                <button type="submit" class="btn btn-danger">Deletar instituição</button>
                <button type="button" class="btn btn-secondary" onclick="window.history.back()">Voltar</button>
            </div>
        </form>
    </body>
</html>

AcessoBolsas/institution/templates/institution/editInstitution.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Editar Instituição {{ form.instance.nome }}</title>
</head>
<body>
    <h3 class='text-center'>Editar Instituição</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Atualizar Instituição</button>
    </form>
</body>
</html>
{% endblock content %}

AcessoBolsas/institution/templates/institution/listInstitutions.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Lista de Instituções </title>
    <head>
    <body>
        <a href="{% url 'institution:create-institution' %}">Criar Instituição</a>
        <h1> Lista de Instituições </h1>
        <table>
            <tr><th>nome</th><th>cnpj</th><th>contato</th></tr>
            {% if institutions %}
                {% for institution in institutions %}
                    <tr>
                        <td>{{ institution.nome }}</td><td>{{ institution.cnpj }}</td><td>{{ institution.contato }}</td>
                        <td><a href="{% url 'institution:edit-institution' slug=institution.slug %}">Editar</a> / 
                             <a href="{% url 'institution:profile-institution' slug=institution.slug %}">View</a> / 
                             <a href="{% url 'institution:delete-institution' slug=institution.slug %}">Deletar</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr><th colspan="5">Ainda não tem instituições cadastradas</th></tr>
            {% endif %} 
        </table>
    </body>
</html>

AcessoBolsas/institution/templates/institution/loginInstitution.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>
    <div class="form-container">
        <h2 style="font-family: Inter;">Login Instituição</h2>
        {% if message %}
            <p>{{ message }}</p>
            <form method="POST" action="{% url 'loginInstitution' %}">
                {% csrf_token %}
                <input type="hidden" name="cnpj" value="{{ cnpj }}">
                <div class="spacing">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" id="password" name="password" class="form-input" required>
                </div>
                <button type="submit" class="form-button">Login</button>
            </form>
        {% else %}
            {% if error %}
                <p style="color: red;">{{ error }}</p>
            {% endif %}
            <form method="POST" action="{% url 'loginInstitution' %}">
                {% csrf_token %}
                <div class="spacing">
                    <label for="cnpj" class="form-label">CNPJ:</label>
                    <input type="text" id="cnpj" name="cnpj" class="form-input" required>
                </div>
                <button type="submit" class="form-button">Send Password</button>
            </form>
        {% endif %}
    </div>
</body>



{% endblock content %}

AcessoBolsas/institution/templates/institution/perfil_instituição.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'institution/css/styles.css' %}">
    <title>Perfil Instituições</title>
</head>
<body>
    <div class="linha">
        <div class="menu">
            <img src="{% static 'institution/img/menu.svg' %}" class="menu_image">
        </div>
        <div class="logout">
            <button class="botão_logout" type="button" onclick="alert('você escolheu sair')">Log out</button>
        </div>
    </div>
    <div class="head">
        <div class="logo">
            <img src="{% static 'institution/img/logo.png' %}" class="logo_image">
        </div>
    </div>

    <div class="usuário">
        <div class="pfp">
            <img src="{{ perfil.foto_perfil.url }}" class="user_image">
        </div>

        <div class="textos">
            <p>Nome da instituição: {{ perfil.nome }}<br></p>
            <p>CNPJ: {{ perfil.cnpj }}<br></p>
            <p>Contatos: {{ perfil.contato }}<br></p>
            <p>Endereço: {{ perfil.endereco }}<br></p>
            <p>Sobre a Instituição: {{ perfil.descricao }}<br></p>
        </div>
    </div>

    <div class="botões">
        <button class="botão_editar" type="button">Editar perfil</button>
        <button class="botão_ver_bolsas" type="button">Bolsas Cadastradas</button>
        <button class="botão_deletar" type="button">Deletar Perfil</button>
    </div>

    <footer>
        <p>Footer</p>
    </footer>
</body>
</html>

AcessoBolsas/institution/templates/institution/verify_password.html
<!DOCTYPE html>
<html>
<head>
    <title>Verify Password</title>
</head>
<body>
    <h2>Verify Password</h2>
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="cnpj" value="{{ cnpj }}">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

AcessoBolsas/institution/templates/institution/viewInstitution.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>

    <div class="usuário">
        <div class="pfp">
            <img src="{{ institution.fotoPerfil.url }}" class="user_image">
        </div>

        <div class="textos_instituicao">
            <p>Nome da instituição: {{ institution.nome }}<br></p>
            <p>CNPJ: {{ institution.cnpj }}<br></p>
            <p>Contatos: {{ institution.contato }}<br></p>
            <p>Endereço: {{ institution.endereco }}<br></p>
            <p>Sobre a Instituição: {{ institution.descricao }}<br></p>
        </div>
    </div>
    {% if institution.nome == nameInstitution %}
        <div class="botões">
            <button class="botão_editar" onclick="location.href='{% url 'institution:edit-institution' slug=institution.slug %}'" type="button">Editar perfil</button>
            <button class="botão_ver_bolsas"  onclick="location.href='{% url 'institution:institution-scholarships' slug=institution.slug %}'" type="button">Bolsas Cadastradas</button>
            <button class="botão_deletar" onclick="location.href='{% url 'institution:delete-institution' slug=institution.slug %}'" type="button">Deletar Perfil</button>
            <button class="botão_editar" onclick="location.href='{% url 'scholarship:create-scholarship' %}'" type="button">Criar bolsas</button>
        </div>
    {% endif %}

</body>

{% endblock content %}