AcessoBolsas/AcessoBolsas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from AcessoBolsas.views import HomeView
from AcessoBolsas.views import SignUp
from AcessoBolsas.views import SignIn
from user.views import (
    loginUser,
    logoutUser,
    registerUser,
    myAccountUser,
)
from institution.views import (
    loginInstitution,
    logoutInstitution,
    createInstitution,
    myAccountInstitution,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView , name='home'),
    path('user/', include('user.urls')),
    path('<username>/my_account/', myAccountUser, name='my_account'),
    path('<slugInstitution>/my_account_institution/', myAccountInstitution, name='my_account_institution'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('loginInstitution/', loginInstitution, name='loginInstitution'),
    path('logoutInstitution/', logoutInstitution, name='logoutInstitution'),
    # path('scholarship/', include('scholarship.urls')),
    path('institution/', include('institution.urls')),
    path('sign_in/', SignIn, name='sign_in'),
    path('sign_up/', SignUp, name='sign_up'),
    path('sign_up/institution/', createInstitution, name='sign_up_institution'),
    path('sign_up/user/', registerUser, name='sign_up_user'),
    path('scholarship/', include('scholarship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AcessoBolsas/institution/urls.py
from django.urls import path
from institution import views

app_name ='institution'

urlpatterns = [
    path('<slug>/profile/', views.viewInstitution, name='profile-institution'),
    path('<slug>/edit/', views.editInstitution, name='edit-institution'),
    path('', views.listInstitutions, name='list-institution'),
    path('create/', views.createInstitution, name='create-institution'),
    path('<slug>/delete/', views.deleteInstitution, name='delete-institution'),
    path('institution/<slug:slug>/scholarships/', views.institutionScholarships, name='institution-scholarships'),

]

AcessoBolsas/scholarship/urls.py
from django.urls import path
from scholarship import views

app_name = 'scholarship'

urlpatterns = [
    path('create/', views.createScholarship, name='create-scholarship'),
    path('<slug>/edit/', views.editScholarship, name='edit-scholarship'),
    path('<slug>/profile/', views.viewScholarship, name='profile-scholarship'),
    path('<slug>/delete/', views.deleteScholarship, name='delete-scholarship'),
    path('inscricoes/', views.listar_scholarships_user, name='listar-scholarships-user'),  # Colocando antes do path com slug
    path('', views.listScholarships, name='list-scholarship'),
    path('<slug>/', views.viewScholarship, name='view-scholarship'),
    path('inscrever/<slug>/', views.inscrever_scholarship, name='inscrever-scholarship'),
]

AcessoBolsas/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerUser, name='register-user'),
    path('<slug>/edit/', views.editUser, name='edit-user'),
    path('<slug>/delete/', views.deleteUser, name='delete-user'),
    path('<slug>/profile/', views.viewUser, name='profile-user'),
    path('', views.listUsers, name='list-user'),
]

AcessoBolsas/scholarship/models.py
from django.db import models
from random import randint
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.contrib.auth import get_user_model

# Create your models here.

SLUG_LIST = []

class Scholarship(models.Model):
    id = models.AutoField(primary_key=True, null=False, blank=False, unique=True)
    titulo = models.CharField(help_text='Título da bolsa', max_length=150, null=False, blank=False)
    tipoBolsa = models.CharField(help_text='Tipo da bolsa', max_length=100, null=False, blank=False)
    descricao = models.TextField(help_text='Descrição da bolsa', max_length=5000, null=False, blank=False)
    dataPrazo = models.DateField(help_text='Data limite para a realização da bolsa', verbose_name='Data limite', null=False, blank=False)
    dataPostada = models.DateField(help_text='Data da postagem da bolsa', auto_now_add=True, verbose_name='Data da postagem')
    dataAtualizada = models.DateField(help_text='Data da atualização da bolsa', auto_now=True, verbose_name='Data da atualização')
    instituicao = models.ForeignKey('institution.Institution', on_delete=models.CASCADE)
    fotoPerfil = models.ImageField(upload_to='scholarship', default='default.jpg', null=True, blank=True)
    slug = models.SlugField(blank=True, unique=True)
    inscritos = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='scholarships_inscritos')

    def __str__(self):
        return self.titulo

def pre_save_scholarship_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug_random = 0
        while slug_random not in SLUG_LIST:
            slug_random = randint(1, 1000)
            SLUG_LIST.append(slug_random)
        instance.slug = slugify(instance.instituicao.nome + "-" + str(slug_random))

pre_save.connect(pre_save_scholarship_receiver, sender=Scholarship)

AcessoBolsas/scholarship/forms.py
from django import forms
from scholarship.models import Scholarship

class ScholarshipRegisterForm(forms.ModelForm):
    class Meta:
        model = Scholarship
        fields = ['titulo', 'tipoBolsa', 'descricao', 'dataPrazo', 'fotoPerfil']

class ScholarshipUpdateForm(forms.ModelForm):
    class Meta:
        model = Scholarship
        fields = ['titulo', 'tipoBolsa', 'descricao', 'dataPrazo', 'fotoPerfil']

    def save(self, commit=True):
        scholarship = self.instance
        scholarship.titulo = self.cleaned_data['titulo']
        scholarship.tipoBolsa = self.cleaned_data['tipoBolsa']
        scholarship.descricao = self.cleaned_data['descricao']
        scholarship.dataPrazo = self.cleaned_data['dataPrazo']

        if self.cleaned_data['fotoPerfil']:
            scholarship.fotoPerfil = self.cleaned_data['fotoPerfil']

        if commit:
            scholarship.save()
        return scholarship

AcessoBolsas/scholarship/views.py
from django.shortcuts import render, redirect, get_object_or_404
from scholarship.forms import ScholarshipRegisterForm, ScholarshipUpdateForm
from django.contrib import messages
from institution.models import Institution
from scholarship.models import Scholarship
from django.http import JsonResponse
from django.http import HttpResponse
import json

# Create your views here.

def createScholarship(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    institution = get_object_or_404(Institution, slug=request.COOKIES.get('slugInstitution'))
    if not institution.checked and not institution.logged:
       return redirect("loginInstitution")
    
    form = ScholarshipRegisterForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        scholarship = form.save(commit=False)
        institution_author = institution
        scholarship.instituicao = institution_author
        scholarship.save()
        form = ScholarshipRegisterForm()
        messages.success(request, 'Bolsa cadastrada com sucesso!')
        return redirect('home')
    
    context['form'] = form        
    return render(request, 'scholarship/createScholarship.html', context)


def editScholarship(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    scholarship = get_object_or_404(Scholarship, slug=slug)
    institution = scholarship.instituicao

    if not institution.checked or not institution.logged:
        return redirect("loginInstitution")
    
    if request.method == 'POST':
        form = ScholarshipUpdateForm(request.POST, request.FILES, instance=scholarship)
        if form.is_valid():
            form.save()
            messages.success(request, 'Bolsa atualizada com sucesso!')
            return redirect('home')
        else:
            messages.warning(request, 'Erro ao atualizar a bolsa. Tente novamente.')
    else:
        form = ScholarshipUpdateForm(instance=scholarship)

    context['form'] = form
    return render(request, 'scholarship/editScholarship.html', context)


def viewScholarship(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    
    scholarship = get_object_or_404(Scholarship, slug=slug)
    context['scholarship'] = scholarship

    if request.method == 'POST':
        data = json.loads(request.body)
        if 'url' in data:
            url = data.get('url', '')
            print(f"URL recebida: {url}")
            return JsonResponse({'status': 'success', 'url': url})
        elif 'action' in data and data['action'] == 'contact':
            contato = scholarship.instituicao.contato
            print(f"Contato da instituição: {contato}")
            return JsonResponse({'status': 'success', 'contato': contato})

    return render(request, 'scholarship/viewScholarship.html', context)


def deleteScholarship(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    
    scholarship = get_object_or_404(Scholarship, slug=slug)
    institution = scholarship.__getattribute__('instituicao')
    if not institution.checked and not institution.logged:
        return redirect("loginInstitution")

    if request.POST:
        scholarship.fotoPerfil.delete()
        scholarship.delete()
        messages.success(request, 'Bolsa deletada com sucesso!')
        return redirect("home")
    
    context['scholarship'] = scholarship
    return render(request, 'scholarship/deleteScholarship.html', context)

def listScholarships(request):
    context = {}
    
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    
    scholarships = Scholarship.objects.all()
    context['scholarships'] = scholarships
    return render(request,'scholarship/listScholarships.html', context)

def inscrever_scholarship(request, slug):
    scholarship = get_object_or_404(Scholarship, slug=slug)
    if request.method == 'POST':
        # Adicione aqui a lógica para inscrever o usuário na bolsa
        # Por exemplo, adicionar o usuário a uma lista de inscritos na bolsa
        return redirect('scholarship:view-scholarship', slug=scholarship.slug)
    return HttpResponse(status=405)  # Método não permitido se não for POST

def listar_scholarships_user(request):
    user_scholarships = Scholarship.objects.filter(inscritos=request.user)
    return render(request, 'scholarship/listScholarshipsUser.html', {'scholarships': user_scholarships})

AcessoBolsas/scholarship/templates/scholarship/createScholarship.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Criar Bolsa</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            font-weight: bold;
            margin-bottom: 5px;
            display: block;
        }
        .form-group input, .form-group textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .form-group input[type="file"] {
            padding: 3px;
        }
        .form-group button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        .form-group button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="text-center">Criar Bolsa</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_titulo" class="form-label">Título</label>
                <input type="text" name="titulo" class="form-control" id="id_titulo" placeholder="Título da bolsa" required autofocus>
            </div>
            <div class="form-group">
                <label for="id_tipoBolsa" class="form-label">Tipo da bolsa</label>
                <input type="text" name="tipoBolsa" class="form-control" id="id_tipoBolsa" placeholder="Tipo da bolsa" required>
            </div>
            <div class="form-group">
                <label for="id_descricao" class="form-label">Descrição</label>
                <textarea name="descricao" rows="10" class="form-control" id="id_descricao" placeholder="Descrição completa da bolsa" required></textarea>
            </div>
            <div class="form-group">
                <label for="id_dataPrazo" class="form-label">Data limite</label>
                <input type="date" name="dataPrazo" class="form-control" id="id_dataPrazo" placeholder="Data limite para a realização da bolsa" required>
            </div>
            <div class="form-group">
                <label for="id_fotoPerfil" class="form-label">Foto de Perfil</label>
                <input type="file" name="fotoPerfil" class="form-control" id="id_fotoPerfil">
            </div>
            <div class="form-group">
                <button type="submit">Criar Bolsa</button>
            </div>
        </form>
    </div>
</body>
</html>
{% endblock content %}

AcessoBolsas/scholarship/templates/scholarship/deleteScholarship.html
{% load static %}
<!doctype html>
<html lang="en">
    <title>Deletar {{scholarship.titulo}}</title>
    <head>
        <h3 class='text-center'>Deletar Bolsa</h3>
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class='text-center'>Tem certeza que deseja deletar esssa bolsa?</h3>
            <div class="mt-3 text-center">
                <button type="submit" class="btn btn-danger">Deletar bolsa</button>
                <button type="button" class="btn btn-secondary" onclick="window.history.back()">Voltar</button>
            </div>
        </form>
    </body>
</html>

AcessoBolsas/scholarship/templates/scholarship/editScholarship.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Editar Bolsa {{ form.instance.titulo }}</title>
</head>
<body>
    <h3 class='text-center'>Editar Bolsa</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Atualizar Bolsa</button>
    </form>
</body>
</html>
{% endblock content %}

AcessoBolsas/scholarship/templates/scholarship/listScholarships.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Lista de Bolsas </title>
    <head>
    <body>
        <a href="{% url 'scholarship:create-scholarship' %}">Criar Bolsa</a>
        <h1> Lista de Bolsas </h1>
        <table>
            <tr><th>titulo</th><th>tipoBolsa</th><th>descricao</th></tr>
            {% if scholarships %}
                {% for scholarship in scholarships %}
                    <tr>
                        <td>{{ scholarship.titulo }}</td><td>{{ scholarship.tipoBolsa }}</td><td>{{ scholarship.descricao }}</td>
                        <td><a href="{% url 'scholarship:edit-scholarship' slug=scholarship.slug %}">Editar</a> /
                            <a href="{% url 'scholarship:profile-scholarship' slug=scholarship.slug %}">View</a> /  
                            <a href="{% url 'scholarship:delete-scholarship' slug=scholarship.slug %}">Deletar</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr><th colspan="5">Ainda não tem bolsas cadastradas</th></tr>
            {% endif %} 
        </table>
    </body>
</html>

AcessoBolsas/scholarship/templates/scholarship/listScholarshipsUser.html
{% extends 'base2.html' %}

{% block content %}
<div class="div-recomendacoes">
    <p class="text-recomendacoes">Bolsas de estudos inscritas: </p>
    <div class="recomendacoes">
        <div class="left-column col-lg-7 offset-lg-0">  
            {% for scholarship in scholarships %}
            <div>
                <div class="container">
                    <div class="row">
                        <div class="card text-bg-dark">
                            <div class="card-body my-2">
                                <div class="content">
                                    <a href='{% url 'scholarship:profile-scholarship' scholarship.slug %}' style="text-decoration: none !important">
                                        <h2 class="card-titulo" style="font-family: Inter;">{{scholarship.titulo}}</h2>
                                    </a>
                                    <p class="card-text text-bg-dark" style="font-family: Inter;">{{scholarship.instituicao}}</p>
                                    <p class="card-text text-bg-dark" style="font-family: Inter;">{{scholarship.tipoBolsa}}</p>
                                </div>
                                <div class="image">
                                    <img src="{{ scholarship.fotoPerfil.url }}" alt="{{ scholarship.titulo }}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% empty %}
                <p>Sem Bolsas</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

AcessoBolsas/scholarship/templates/scholarship/viewScholarship.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>
    <p class="voltar" onclick="history.go(-1);"><img src="{% static 'AcessoBolsas/img/seta_back.png' %}" class="img_seta" /><u>Voltar</u></p>
    <div class="div-recomendacoes">
        <div class="recomendacoes_post">
            <div class="header_inst">
                <div>
                    <div class="nome_inst">
                        <p class="pnome_inst">Nome da Instituição: {{ scholarship.instituicao.nome }}</p>
                    </div>
                    <div class="tipo_bolsa">
                        <p class="ptipo_bolsa"><u>Tipo de Bolsa: {{ scholarship.tipoBolsa }}</u></p>
                    </div>
                    <div class="desc_inst">
                        <p class="pdesc_inst">Descrição:</p>
                        <p style="margin-left: 25px; max-width: 350px;">{{ scholarship.descricao }}</p>
                    </div>
                </div>
                <div class="foto_inst">
                    <img class="img_inst" src="{{ scholarship.fotoPerfil.url }}" />
                </div>
            </div>
            <div class="tags_anuncio">
                <div class="center_tags_anuncio">
                    <div class="anuncio">
                        <p class="panuncio">Prazo de inscrição: {{scholarship.dataPrazo}}</p>
                    </div>
                </div>
            </div>
            <div class="bottom_inst">
                <div class="div_coment">
                    <!-- <p class="coment_title"><i>Comentários & Perguntas:</i></p>
                    <div class="coment"><i>*Exemplo de comentario*</i></div> -->
                </div>
                {% if scholarship.instituicao.nome == nameInstitution %}
                    <div class="buttons_inst">
                        <button class="see_profile" onclick="location.href='{% url 'scholarship:edit-scholarship' slug=scholarship.slug %}'">Editar bolsa</button>
                        <button class="see_profile" onclick="location.href='{% url 'institution:profile-institution' slug=scholarship.instituicao.slug %}'">Ver perfil</button>
                        <button class="see_profile" onclick="location.href='{% url 'scholarship:delete-scholarship' slug=scholarship.slug %}'">Deletar bolsa</button>
                    </div>
                {% else %}
                    <div class="buttons_inst">
                        <button class="share" onclick="shareLink()">Compartilhar</button>
                        {% if user.is_authenticated %}
                            <form method="POST" action="{% url 'scholarship:inscrever-scholarship' scholarship.slug %}">
                                {% csrf_token %}
                                <button type="submit" class="subs">Inscrever-se na bolsa</button>
                            </form>
                        {% else %}
                            <p><a href="{% url 'login' %}">Faça login</a> para se inscrever.</p>
                        {% endif %}
                        <button class="contact" onclick="contactInstitution()">Entrar em contato</button>
                        <button class="see_profile" onclick="location.href='{% url 'institution:profile-institution' slug=scholarship.instituicao.slug %}'">Ver perfil</button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        function shareLink() {
            const currentURL = window.location.href;
        
            fetch(window.location.pathname, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken'),
                },
                body: JSON.stringify({ url: currentURL })
            })
            .then(response => response.json())
            .then(data => console.log('Success:', data))
            .catch((error) => console.error('Error:', error));
        }
        
        function contactInstitution() {
            fetch(window.location.pathname, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken'),
                },
                body: JSON.stringify({ action: 'contact' })
            })
            .then(response => response.json())
            .then(data => console.log('Success:', data))
            .catch((error) => console.error('Error:', error));
        }
        
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>
</body>

{% endblock content %}