AcessoBolsas/AcessoBolsas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from AcessoBolsas.views import HomeView
from AcessoBolsas.views import SignUp
from AcessoBolsas.views import SignIn
from user.views import (
    loginUser,
    logoutUser,
    registerUser,
    myAccountUser,
)
from institution.views import (
    loginInstitution,
    logoutInstitution,
    createInstitution,
    myAccountInstitution,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView , name='home'),
    path('user/', include('user.urls')),
    path('<username>/my_account/', myAccountUser, name='my_account'),
    path('<slugInstitution>/my_account_institution/', myAccountInstitution, name='my_account_institution'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('loginInstitution/', loginInstitution, name='loginInstitution'),
    path('logoutInstitution/', logoutInstitution, name='logoutInstitution'),
    # path('scholarship/', include('scholarship.urls')),
    path('institution/', include('institution.urls')),
    path('sign_in/', SignIn, name='sign_in'),
    path('sign_up/', SignUp, name='sign_up'),
    path('sign_up/institution/', createInstitution, name='sign_up_institution'),
    path('sign_up/user/', registerUser, name='sign_up_user'),
    path('scholarship/', include('scholarship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AcessoBolsas/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerUser, name='register-user'),
    path('<slug>/edit/', views.editUser, name='edit-user'),
    path('<slug>/delete/', views.deleteUser, name='delete-user'),
    path('<slug>/profile/', views.viewUser, name='profile-user'),
    path('', views.listUsers, name='list-user'),
]

AcessoBolsas/user/models.py
from django.db import models
from django.utils.text import slugify
from random import randint
from django.db.models.signals import post_delete, pre_save
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

SLUG_LIST = []

class AdminMyAccount(BaseUserManager):

    def create_user(self, username, email, nome,  password = None):
        if not username:
            raise ValueError("Usuário precisa ter um nome de usuário.")
        if not email:
            raise ValueError("Usuário precisa ter um email.")
        if not nome:
            raise ValueError("Usuário precisa ter um nome.")
        
        user = self.model(
            username = username,
            email = self.normalize_email(email),
            nome = nome,
        )
        user.set_password(password)
        user.save(using=self._db)

        return user
    
    def create_superuser(self, username, email, nome, password):
        user = self.create_user(
            username = username,
            email = self.normalize_email(email),
            nome = nome,
            password = password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser):
    SEXO_CHOICES = (
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
        ('Outro', 'Outro'),
    )

    id = models.AutoField(primary_key=True, null=False, blank=False, unique=True)

    username = models.CharField(help_text='Informe o nome de usuário', max_length=100, null=False, blank=False, unique=True)

    nome = models.CharField(help_text='Informe o nome', max_length=100, null=False, blank=False)

    email = models.EmailField(help_text='Informe o email', max_length=254, null=False, blank=False, unique=True) 

    telefone = models.CharField(help_text='Informe o numéro de telefone', max_length=20, null=True, blank=True)

    dataNascimento = models.DateField(help_text='Informe a data de nascimento', null=True, blank=True)

    sexo = models.CharField(help_text='Informe o sexo', max_length=9, null=True, blank=True, choices=SEXO_CHOICES)

    fotoPerfil = models.ImageField(upload_to='perfil_usuario', default='default.jpg', null=True, blank=True)

    slug = models.SlugField(blank=True, unique=True)

    is_admin = models.BooleanField(default=False)
    
    is_active = models.BooleanField(default=True)
    
    is_staff = models.BooleanField(default=False)
    
    is_superuser = models.BooleanField(default=False)


    objects = AdminMyAccount()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS=['nome','email']

    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj = None):
        return self.is_admin
    
    def has_module_perms(self,app_label):
        return True
    
def pre_save_user_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug_random = 0
        while slug_random not in SLUG_LIST:
            slug_random = randint(1, 1000)
            SLUG_LIST.append(slug_random)

        instance.slug = slugify(instance.username + "-" + str(slug_random))

pre_save.connect(pre_save_user_receiver, sender=User)

AcessoBolsas/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import authenticate
from user.models import User


class UserRegisterForm(UserCreationForm):

    email = forms.EmailField(max_length=254, help_text='Obrigatório! Informe o seu email.')
    
    class Meta:
        model = User
        fields = ('username', 'email', 'nome', 'password1', 'password2', 'telefone', 'dataNascimento', 'sexo', 'fotoPerfil')


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'nome', 'telefone', 'dataNascimento', 'sexo', 'fotoPerfil')

    def save(self, commit=True):
        user = self.instance
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.nome = self.cleaned_data['nome']
        user.telefone = self.cleaned_data['telefone']
        user.dataNascimento = self.cleaned_data['dataNascimento']
        user.sexo = self.cleaned_data['sexo']

        if self.cleaned_data['fotoPerfil']:
            user.fotoPerfil = self.cleaned_data['fotoPerfil']

        if commit:
            user.save()

        return user

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            try:
                user = User.objects.exclude(pk=self.instance.pk).get(email=email)
            except User.DoesNotExist:
                return email
            raise forms.ValidationError('Email "%s" já sendo utilizado.' % email)
        
    def clean_username(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            try:
                user = User.objects.exclude(pk=self.instance.pk).get(username=username)
            except User.DoesNotExist:
                return username
            raise forms.ValidationError('Username "%s" já sendo utilizado.' % username)
        

class UserAuthForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password')
    
    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError('Usuário ou senha inválidos.')

AcessoBolsas/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from user.models import User
from user.forms import UserRegisterForm, UserUpdateForm, UserAuthForm
from institution.models import Institution

# Create your views here.

@csrf_protect
def registerUser(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            
            if user is not None:
                login(request, user)
                messages.success(request, 'Usuário cadastrado com sucesso!')
                return redirect('home')
            else:
                messages.error(request, 'Erro ao cadastrar usuário!')
                return redirect('login')
        else:
            context['registrationForm'] = form
    else:
        form = UserRegisterForm()
        context['registrationForm'] = form

    return render(request, 'user/registerUser.html', context)

def editUser(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    if not request.user.is_authenticated:
        return redirect("login")

    user = get_object_or_404(User, slug=slug)

    if request.method == 'POST':
        form = UserUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User atualizado com sucesso!')
            return redirect('home')
        else:
            messages.warning(request, 'E-mail ou username indisponíveis. Tente novamente.')
    else:
        form = UserUpdateForm(instance=user)

    context['updateForm'] = form

    return render(request, 'user/editUser.html', context)

def deleteUser(request, slug):
    if not request.user.is_authenticated:
        return redirect("login")
    
    context = {}
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password, slug=slug)

        if user:
            user.delete()
            logout(request)
            messages.success(request, 'Usuário deletado com sucesso!')
            return redirect("home")
        else:
            messages.warning(request, 'Username ou senha incorretos! Tente novamente.')

    return render(request, 'user/deleteUser.html', context)

def viewUser(request, slug):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    user = get_object_or_404(User, slug=slug)
    context['user'] = user
    return render(request, 'user/viewUser.html', context)

def listUsers(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    users = User.objects.all()
    context['users'] = users
    return render(request,'user/listUsers.html', context)

def logoutUser(request):
    logout(request)
    messages.success(request, 'Logout feito com sucesso!')
    return redirect("home")

def loginUser(request):
    context = {}

    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')

    response = redirect('home')
    if request.COOKIES.get('logged') == True:
        institution = Institution.objects.get(slug=request.COOKIES.get('slugInstitution'))
        institution.logged = False
        response.set_cookie('logged', False)
        response.set_cookie('slugInstitution', None)
        response.set_cookie('nameInstitution', None)
        institution.save()
        
    user = request.user
    if user.is_authenticated:
        return redirect("home")
    
    if request.method == 'POST':
        form = UserAuthForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                messages.success(request, 'Login feito com sucesso!')
                return response
    
    else:
        form = UserAuthForm()

    context['loginForm'] = form
    return render(request, 'user/loginUser.html', context)

def myAccountUser(request, username):
    context = {}
    
    context['slugInstitution'] = request.COOKIES.get('slugInstitution')
    context['nameInstitution'] = request.COOKIES.get('nameInstitution')
    context['institutionLogged'] = request.COOKIES.get('logged')
    
    user = get_object_or_404(User, username=username)
    context['user'] = user
    return render(request,'user/viewUser.html', context)

AcessoBolsas/user/templates/user/deleteUser.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!doctype html>
<html lang="en">
    <title>Deletar Usuário</title>
    <head>
        <h3 class='text-center'>Deletar Usuário</h3>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 text-center">
                <h3>Tem certeza que deseja apagar sua conta?</h3>
            </div>
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                <input type="text" name="username" class="form-control" id="id_username" placeholder="Digite seu username" required>
            </div>
            <div class="mb-3">
                <label for="id_password" class="form-label">Senha</label>
                <input type="password" name="password" class="form-control" id="id_password" placeholder="Digite sua senha" required>
            </div>
            {% if failed_message %}
            <p style="color: red; text-align: center;">{{ failed_message }}</p>
            {% endif %}
            <div class="text-center">
                <button type="submit" class="btn btn-danger">Apagar</button>
            </div>
        </form>
    </body>

{% endblock content %}

AcessoBolsas/user/templates/user/editUser.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">

<body>
    <h3 class='text-center'>Editar Usuário</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ updateForm.as_p }}
        <button type="submit" class="btn btn-primary">Atualizar Usuário</button>
    </form>
</body>
</html>
{% endblock content %}

AcessoBolsas/user/templates/user/listUsers.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Lista de Usuários </title>
    <head>
    <body>
        <a href="{% url 'user:register-user' %}">Criar Usuário</a>
        <h1> Lista de Usuários </h1>
        <table>
            <tr><th>Email</th><th>Nome</th><th>Username</th></tr>
            {% if users %}
                {% for user in users %}
                    <tr>
                        <td>{{ user.email }}</td><td>{{ user.nome }}</td><td>{{ user.username }}</td>
                        <td><a href="{% url 'user:edit-user' slug=user.slug %}">Editar</a> /
                            <a href="{% url 'user:profile-user' slug=user.slug %}">View</a> / 
                            <a href="{% url 'user:delete-user' slug=user.slug %}">Deletar</a></td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr><th colspan="5">Ainda não tem usuários cadastrados</th></tr>
            {% endif %} 
        </table>
    </body>
</html>

AcessoBolsas/user/templates/user/loginUser.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<body>
    <div class="login-container">
        <h2 class="titulo_login">Login</h2>
        <div class="messages">
            {% if messages %}
                {% for message in messages %}
                    <p class="{{ message.tags }}">{{ message }}</p>
                {% endfor %}
            {% endif %}
        </div>
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            {{ loginForm.as_p }}
            <button type="submit" class="btn_login">Login</button>
        </form>
    </div>
</body>
{% endblock content %}

AcessoBolsas/user/templates/user/registerUser.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>
    <p class="voltar" onclick="history.go(-1);"><img src="{% static '\institution\img\seta_back.png' %}" class="img_seta" /><u>Voltar</u></p>
    <div class="div-box">
        <div class="box_cadastro_usu">
            <div class="questions_cadastro_usu">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p class="headerInput">Nome Completo: </p>
                    <input type="text" class="inputCadastro" name="nome" placeholder="Nome:" required/>
                    
                    <p class="headerInput">Telefone: </p>
                    <input type="number" class="inputCadastro" name="telefone" placeholder="Tel:" />

                    <p class="headerInput">E-mail: </p>
                    <input type="email" class="inputCadastro" name="email" placeholder="E-mail:" required/>

                    <p class="headerInput">Data de nascimento: </p>
                    <input type="date" class="inputCadastro" name="dataNascimento" placeholder="Data:" />

                    <p class="headerInput">Sexo: </p>
                    <select class="select_genero" name="sexo" >
                        <option value="" disabled selected>Selecione</option>
                        <option>Feminino</option>
                        <option>Masculino</option>
                        <option>Outro</option>
                    </select>

                    <p class="headerInput">Username: </p>
                    <input type="text" class="inputCadastro" name="username" placeholder="Login:" required/>

                    <p class="headerInput">Defina sua senha: </p>
                    <input type="password" class="inputCadastro" name="password1" placeholder="Senha:" required/>
                    
                    <p class="headerInput">Confirme sua senha: </p>
                    <input type="password" class="inputCadastro" name="password2" placeholder="Senha:" required/>

                    {% for field in registrationForm %}
                    <p>
                        {% for error in field.errors %}
                        <p style="color: red;">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    {% if registrationForm.non_field_errors %}
                    <div style="color: red;">
                        <p>{{ registrationForm.non_field_errors }}</p>
                    </div>
                    {% endif %}
                    <button type="submit" class="cadastre-se">Cadastre-se</button>
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'AcessoBolsas/js/script.js' %}"></script>

</body>

{% endblock content %}

AcessoBolsas/user/templates/user/registerUser1.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title> Registrar Usuário </title>
    </head>
    <body>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                <input type="text" name="username" class="form-control" id="id_username" placeholder="Username" required autofocus>
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="id_email" placeholder="Email" required>
            </div>
            <div class='mb-3 form-group'>
                <label for='id_nome' class='form-label'>Nome</label>
                <input type='text' name='nome' class='form-control' id='id_nome' placeholder='Nome' required>
            </div>
            <div class="mb-3">
                <label for="id_password1" class="form-label">Senha</label>
                <input type="password" name="password1" class="form-control" id="id_password1" placeholder="Senha" required>
            </div>
            <div class="mb-3">
                <label for="id_password2" class="form-label">Confirmação da senha</label>
                <input type="password" name="password2" class="form-control" id="id_password2" placeholder="Confirmação da senha" required>
            </div>
            <div class="mb-3">
                <label for="id_telefone" class="form-label">Telefone</label>
                <input type="text" name="telefone" class="form-control" id="id_telefone" placeholder="Telefone">
            </div>
            <div class="mb-3">
                <label for="id_dataNascimento" class="form-label">Data de Nascimento</label>
                <input type="date" name="dataNascimento" class="form-control" id="id_dataNascimento" placeholder="Telefone">
            </div>
            <div class="mb-3">
                <label for="id_sexo" class="form-label">Sexo</label>
                <input type="text" name="sexo" class="form-control" id="id_sexo" placeholder="Sexo">
            </div>
            {% for field in registrationForm %}
            <p>
                {% for error in field.errors %}
                <p style="color: red;">{{ error }}</p>
                {% endfor %}
            </p>
            {% endfor %}
            {% if registrationForm.non_field_errors %}
            <div style="color: red;">
                <p>{{ registrationForm.non_field_errors }}</p>
            </div>
            {% endif %}
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Registrar</button>
            </div>
        </form>
    </body>
</html>

AcessoBolsas/user/templates/user/viewUser.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>

<body>

    <div class="usuário">
        <div class="pfp">
            <img src="{{ user.fotoPerfil.url }}" class="user_image">
        </div>

        <div class="textos_instituicao">
            <p>Usuário(a): {{ user.username }}<br></p>
            <p>Nome: {{ user.nome }}<br></p>
            <p>Email: {{ user.email }}<br></p>
            <p>Telefone: {{ user.telefone }}<br></p>
            <p>Data de nascimento: {{ user.dataNascimento }}<br></p>
	    <p>Sexo: {{ user.get_sexo_display }}<br></p>
        </div>
    </div>
    {% if request.user.username == user.username %}
        <div class="botões">
            <button class="botão_editar" onclick="location.href='{% url 'user:edit-user' slug=user.slug %}'" type="button">Editar perfil</button>
            <button class="botão_deletar" onclick="location.href='{% url 'user:delete-user' slug=user.slug %}'" type="button">Deletar Perfil</button>
        </div>
    {% endif %}

</body>

{% endblock content %}