AcessoBolsas/AcessoBolsas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from AcessoBolsas.views import HomeView
from AcessoBolsas.views import SignUp
from AcessoBolsas.views import SignIn
from user.views import (
    loginUser,
    logoutUser,
    registerUser,
    myAccountUser,
)
from institution.views import (
    loginInstitution,
    logoutInstitution,
    createInstitution,
    myAccountInstitution,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView , name='home'),
    path('user/', include('user.urls')),
    path('<username>/my_account/', myAccountUser, name='my_account'),
    path('<slugInstitution>/my_account_institution/', myAccountInstitution, name='my_account_institution'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('loginInstitution/', loginInstitution, name='loginInstitution'),
    path('logoutInstitution/', logoutInstitution, name='logoutInstitution'),
    # path('scholarship/', include('scholarship.urls')),
    path('institution/', include('institution.urls')),
    path('sign_in/', SignIn, name='sign_in'),
    path('sign_up/', SignUp, name='sign_up'),
    path('sign_up/institution/', createInstitution, name='sign_up_institution'),
    path('sign_up/user/', registerUser, name='sign_up_user'),
    path('scholarship/', include('scholarship.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AcessoBolsas/institution/urls.py
from django.urls import path
from institution import views

app_name ='institution'

urlpatterns = [
    path('<slug>/profile/', views.viewInstitution, name='profile-institution'),
    path('<slug>/edit/', views.editInstitution, name='edit-institution'),
    path('', views.listInstitutions, name='list-institution'),
    path('create/', views.createInstitution, name='create-institution'),
    path('<slug>/delete/', views.deleteInstitution, name='delete-institution'),
    path('institution/<slug:slug>/scholarships/', views.institutionScholarships, name='institution-scholarships'),

]

AcessoBolsas/scholarship/urls.py
from django.urls import path
from scholarship import views

app_name = 'scholarship'

urlpatterns = [
    path('create/', views.createScholarship, name='create-scholarship'),
    path('<slug>/edit/', views.editScholarship, name='edit-scholarship'),
    path('<slug>/profile/', views.viewScholarship, name='profile-scholarship'),
    path('<slug>/delete/', views.deleteScholarship, name='delete-scholarship'),
    path('inscricoes/', views.listar_scholarships_user, name='listar-scholarships-user'),  # Colocando antes do path com slug
    path('', views.listScholarships, name='list-scholarship'),
    path('<slug>/', views.viewScholarship, name='view-scholarship'),
    path('inscrever/<slug>/', views.inscrever_scholarship, name='inscrever-scholarship'),
]

AcessoBolsas/user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.registerUser, name='register-user'),
    path('<slug>/edit/', views.editUser, name='edit-user'),
    path('<slug>/delete/', views.deleteUser, name='delete-user'),
    path('<slug>/profile/', views.viewUser, name='profile-user'),
    path('', views.listUsers, name='list-user'),
]

AcessoBolsas/templates/partes/footer.html
{% load static %}
<!DOCTYPE html>


<footer>
    <p>2024 AcessoBolsas.com</p>
</footer>

AcessoBolsas/templates/partes/header.html
{% load static %}
<!DOCTYPE html>


 
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>AcessoBolsas.com</title>
<link href="{% static '/AcessoBolsas/css/style.css' %}" rel="stylesheet" type="text/css" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Outfit:wght@100..900&display=swap"
    rel="stylesheet">


<header>
    <div class="linha_menu">
        <button class="botão-body"><img src="{% static 'img/menu.png' %}" class="menu_image"></button>
        <div class="menu">
            <div class="linha">
                <button class="botão-linha"><img src="{% static 'img/menu.png' %}" class="menu_image"></button>
                <p class="texto_menu">Menu</p>
            </div>

            <div class="textos">
                <p>wedwed</p>
                <p class="clickable" onclick="location.href='{% url 'home' %}'">Inicio</p>
                {% if request.user.is_authenticated %}
                    <p class="clickable" onclick="location.href='{% url 'my_account' username=request.user.username %}'">Perfil</p>
                    <p class="clickable" onclick="location.href='{% url 'scholarship:listar-scholarships-user' %}'">Acompanhar inscrições</p>
                {% elif institutionLogged == True and institutionLogged %}
                    <p class="clickable" onclick="location.href='{% url 'my_account_institution' slugInstitution=slugInstitution %}'">Perfil</p>
                    <p class="clickable" onclick="location.href='{% url 'institution:institution-scholarships' slug=slugInstitution %}'">Bolsas cadastradas</p>
                {% endif %}
            </div>

            <p class="sair">Sair</p>
        </div>

        {% if request.user.is_authenticated %}
            <a class="d-flex align-items-center text-white text-decoration-none" style="margin-left: 650px; font-family: Inter;">
            Bem-Vindo, {{request.user.username}}!
            </a>
        {% elif institutionLogged == True and institutionLogged %}
        <a class="d-flex align-items-center text-white text-decoration-none" style="margin-left: 650px; font-family: Inter;">
            Bem-Vinda, {{nameInstitution}}!
            </a>
        {% endif %}
        
        {% if request.user.is_authenticated %}
        <div class='buttons'>
            <button onclick="location.href='{% url 'logout' %}'" class='btn1'>Logout</button>
            <button onclick="location.href='{% url 'my_account' username=request.user.username %}'" class='btn1'>Minha Conta</button>
        </div>
        {% elif institutionLogged == True and institutionLogged %}
        <div class='buttons'>
            <button onclick="location.href='{% url 'logoutInstitution' %}'" class='btn1'>Logout</button>
            <button onclick="location.href='{% url 'my_account_institution' slugInstitution=slugInstitution %}'" class='btn1'>Minha Conta</button>
        </div>
        {% else %}
            <div class='buttons'>
                <button onclick="location.href='{% url 'sign_in' %}'" class='btn1'>Sign In</button>
                <button onclick="location.href='{% url 'sign_up' %}'" class='btn1'>Sign Up</button>
            </div>
        {% endif %}
    </div>
    <div class='head'>
        <div class="div-logo">
            <div class='logo'>
                <p class="titulo">AcessoBolsas.com</p>
                <img class="pencil_image" src="{% static 'AcessoBolsas/img/pencil.png' %}">
                <div class="input">
                    <form method="GET" action="{% url 'home' %}">
                        <span><img src="{% static 'AcessoBolsas/img/lupa.png' %}" class="input-img" onclick="this.closest('form').submit();"></span>
                        <input class="input-pesquisa" type="text" name="q" placeholder="Search..." value="{{ request.GET.q }}">
                        <span><img src="{% static 'AcessoBolsas/img/filtro.png' %}" class="input-img"></span>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>
<script src="{% static 'js/menu.js' %}"></script>

AcessoBolsas/templates/partes/header2.html
{% load static %}
<!DOCTYPE html>


 
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>AcessoBolsas.com</title>
<link href="{% static '/AcessoBolsas/css/style.css' %}" rel="stylesheet" type="text/css" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Outfit:wght@100..900&display=swap"
    rel="stylesheet">


<header>
    <div class="linha_menu">
        <button class="botão-body"><img src="{% static 'img/menu.png' %}" class="menu_image"></button>
        <div class="menu">
            <div class="linha">
                <button class="botão-linha"><img src="{% static 'img/menu.png' %}" class="menu_image"></button>
                <p class="texto_menu">Menu</p>
            </div>

            <div class="textos">
                <p>wedwed</p>
                <p class="clickable" onclick="location.href='{% url 'home' %}'">Inicio</p>
                {% if request.user.is_authenticated %}
                    <p class="clickable" onclick="location.href='{% url 'my_account' username=request.user.username %}'">Perfil</p>
                    <p class="clickable" onclick="location.href='{% url 'scholarship:listar-scholarships-user' %}'">Acompanhar inscrições</p>
                {% elif institutionLogged == True and institutionLogged %}
                    <p class="clickable" onclick="location.href='{% url 'my_account_institution' slugInstitution=slugInstitution %}'">Perfil</p>
                    <p class="clickable" onclick="location.href='{% url 'institution:institution-scholarships' slug=slugInstitution %}'">Bolsas cadastradas</p>
                {% endif %}
            </div>

            <p class="sair">Sair</p>
        </div>

        {% if request.user.is_authenticated %}
            <a class="d-flex align-items-center text-white text-decoration-none" style="margin-left: 650px; font-family: Inter;">
            Bem-Vindo, {{request.user.username}}!
            </a>
        {% elif institutionLogged == True and institutionLogged %}
        <a class="d-flex align-items-center text-white text-decoration-none" style="margin-left: 650px; font-family: Inter;">
            Bem-Vinda, {{nameInstitution}}!
            </a>
        {% endif %}
        
        {% if request.user.is_authenticated %}
        <div class='buttons'>
            <button onclick="location.href='{% url 'logout' %}'" class='btn1'>Logout</button>
            <button onclick="location.href='{% url 'my_account' username=request.user.username %}'" class='btn1'>Minha Conta</button>
        </div>
        {% elif institutionLogged == True and institutionLogged %}
        <div class='buttons'>
            <button onclick="location.href='{% url 'logoutInstitution' %}'" class='btn1'>Logout</button>
            <button onclick="location.href='{% url 'my_account_institution' slugInstitution=slugInstitution %}'" class='btn1'>Minha Conta</button>
        </div>
        {% else %}
            <div class='buttons'>
                <button onclick="location.href='{% url 'sign_in' %}'" class='btn1'>Sign In</button>
                <button onclick="location.href='{% url 'sign_up' %}'" class='btn1'>Sign Up</button>
            </div>
        {% endif %}
    </div>
    <div class='head'>
        <div class="div-logo">
            <div class='logo'>
                <p class="titulo">AcessoBolsas.com</p>
                <img class="pencil_image" src="{% static 'AcessoBolsas/img/pencil.png' %}">
            </div>
        </div>
    </div>
</header>
<script src="{% static 'js/menu.js' %}"></script>